### ISSUE TITLE
Use function without class?

### ISSUE THREAD

**Issue by scramatte** [wol-soft/php-micro-template#8]
Does it possible to use function without embed them into a class ?

I mean for example:

```php
class Formatters {
   public static function dummy() {
       return 'hello world';
   }
}

```

```php
     ...
        $template = "{{dummy()}}F{{date.format('Ymd')}}-{{sequence.format(8)}}";
        $result = $render->renderTemplateString(
            $template,
            [
               'date' => new DateFormatter,
               'sequence' => new SequenceFormatter,
               'dummy' => Formatters::dummy,
            ]
      ...
```
![image](https://github.com/wol-soft/php-micro-template/assets/188766/1a42399d-1c86-49a4-a09c-9c33a7ad7daa)

**Comment by wol-soft** [comment]
Hi, as of version 1.9.0 you can use callbacks directly in your code. Compare the test cases at https://github.com/wol-soft/php-micro-template/blob/master/tests/RenderTest.php#L369.

Your example throws a PHP syntax error as the callable is defined wrong. Instead of `Formatters::dummy` you must use `[Formatters::class, 'dummy']`.

Cheers
